### ISSUE TITLE
Popout is now just a black screen

### ISSUE THREAD

**Issue by eriknelson** [justinforce/popout_for_youtube#53]
Extension appears to be broken, popping out the video results in a black screen.

**Comment by tauil** [comment]
For me too. :(

**Comment by NeeleyG** [comment]
I just noticed the same problem. I haven't used the extension for a time, but when I tried this morning, just a black box pop-out.

**Comment by justinforce** [comment]
Thank you all for reporting this! I really appreciate your time and effort.

This is due to a new Chrome bug. Unfortunately, I can't do anything about it. If you'd like to help, please star this issue: https://bugs.chromium.org/p/chromium/issues/detail?id=698545

Time permitting, I'll add some kind of notification to the pop out window explaining the situation. I'm the only person working on this thing, and I'm busy the next few days. This is so frustrating! :finnadie:

**Comment by eriknelson** [comment]
@justinforce Upstream bug starred. Thanks for your work!
