### ISSUE TITLE
Video Unavailable.

### ISSUE THREAD

**Issue by kron05** [justinforce/popout_for_youtube#60]
Hello there, 

Just wanted to report a bug where when I look at a specific youtuber's videos(dude called Northernlion), through a popout window I keep getting "Video unavailable" messages.  This hasn't happened to me before, but it happens on an off with this guy and a few other gaming related channels.  Here's a [screenshot](https://imgur.com/a/W9gTF4e) of what I've been seeing.

**Comment by justinforce** [comment]
Thank you for taking the time to report this! I appreciate it. Because the issue is occurring with specific content creators, this seems to be an issue of usage rights. The videos for these creators have been disallowed by the creators or their affiliates from appearing in YouTube's embedded player which is the basis of this extension. So unfortunately this is a Terms of Service kind of obstacle and there's no way around it.
