### ISSUE TITLE
Video Unavailable on "Live"

### ISSUE THREAD

**Issue by irvine48** [justinforce/popout_for_youtube#65]
I looking something can pop-up for live video so i can watch news, and hope there is a option for "Always on Top"

**Comment by justinforce** [comment]
As explained in the extension description, this extension can't provide "always on top" functionality for you. Use other software for this. I've heard that DeskPins is good on Windows. You can find something for your OS by googling.

The extension uses YouTube's embedded player API, so it can only do what embedded YouTube videos do. It can't play live video because they're handled differently by YouTube.

Thanks for taking the time to share your feedback. I appreciate it.
