### ISSUE TITLE
adblock and other extensions don't work in popout

### ISSUE THREAD

**Issue by alivefromupstairs** [justinforce/popout_for_youtube#66]
![image](https://user-images.githubusercontent.com/46059092/50547475-01650e00-0bef-11e9-92bf-7a6a57d24562.png)
I'm trying to remove the suggestion bar at the end and the watch later and the share and info icons. I removed them in chrome but it didn't have any effect on popout. I also use streamkey to enable global media keys to pause/play youtube. and this being a windowed player, it makes sense it should support that. 
and a little complaint. the icon is kinda ugly.

**Comment by justinforce** [comment]
Thank you for your feedback. This extension is very simple and just uses YouTube's API to embed the YouTube player in a window. I'm not doing anything to interfere with your ad blocker. Your issue is probably because the URL of the video window is something like `chrome-extension://poiuaslkjdflkjlkjlfkjsldkjf/popout.html` so your ad blocker rule isn't matching it. There's nothing I can do about this, but you can probably configure your ad blocker to work with the extension if you're brave.

Feel free to submit a replacement icon of the same size and I'll consider it (no guarantees), but keeping up with YouTube's changing aesthetics and layout is a fool's game. I could redesign it, but they'll just change the site and it'll look weird again. And changing it for no very good reason might confuse a lot of people who have been using it for years.

I really appreciate that you care enough to suggest improvements. I work on this alone as a hobby, so I have to be pretty picky about what I commit to.
